package com.ciuc.andrii.file_picker

enum class ToolbarPosition(val styleID: Int) {
    TOP(1), BOTTOM(2)
}

const val TOOLBAR_POSITION = "TOOLBAR_POSITION"
const val ARRAY_EXTENSION = "ARRAY_EXTENSION"
const val TEXT_STYLE_NAME = "TEXT_STYLE_NAME"
const val TEXT_STYLE_DATE = "TEXT_STYLE_DATE"
const val TEXT_STYLE_SIZE = "TEXT_STYLE_SIZE"
const val SIMPLE_DATE_FORMAT = "SIMPLE_DATE_FORMAT"
const val OBJECT_WORD = "OBJECT_WORD"
const val LIST_ITEM_STYLE = "LIST_ITEM_STYLE"
const val LIST_ITEM_SELECTED_STYLE = "LIST_ITEM_SELECTED_STYLE"
const val CUSTOM_LAYOUT_LIST = "CUSTOM_LAYOUT_LIST"
const val CUSTOM_LAYOUT_GRID = "CUSTOM_LAYOUT_GRID"
const val ROOT_BACKGROUND = "ROOT_BACKGROUND"
const val TOOLBAR_BACKGROUND = "TOOLBAR_BACKGROUND"

const val LIST_IMAGE = "LIST_IMAGE"
const val GRID_IMAGE = "GRID_IMAGE"
const val DONE_IMAGE = "DONE_IMAGE"
const val CUSTOM_CHIP_STYLE = "CUSTOM_CHIP_STYLE"
const val TEXT_COUNT_STYLE = "TEXT_COUNT_STYLE"
const val GRID_COUNT = "GRID_COUNT"
const val STORAGE_WORD = "STORAGE_WORD"

val FILE_REQUEST_CODE = 7896

const val CHOSEN_FILES = "CHOSEN_FILES"